language: php

dist: trusty

sudo: false

php:
  - 7.0
  - 7.1

env:
  global:
    - CONSUL_HTTP_ADDR="127.0.0.1:8500"

install:
  - mkdir -p $HOME/bin
  - export PATH="$HOME/bin:$PATH"
  - wget "https://releases.hashicorp.com/consul/1.0.1/consul_1.0.1_linux_amd64.zip"
  - unzip consul_1.0.1_linux_amd64.zip -d $HOME/bin
  - chmod +x $HOME/bin/consul
  - composer install --no-interaction --no-progress --no-suggest --optimize-autoloader

before_script: phpenv config-add ./tests/php.ini

script:
  - ./vendor/bin/phpunit -c phpunit.xml.dist
