language: php

dist: trusty

sudo: false

php:
  - 5.6
  - 7.0
  - 7.1

env:
  global:
    - CONSUL_HTTP_ADDR="127.0.0.1:8500"

install:
  - mkdir -p $HOME/bin
  - export PATH="$HOME/bin:$PATH"
  - wget "https://releases.hashicorp.com/consul/0.8.5/consul_0.8.5_linux_amd64.zip"
  - unzip consul_0.8.5_linux_amd64.zip -d $HOME/bin
  - chmod +x $HOME/bin/consul
  - composer install --no-interaction --no-progress --no-suggest --optimize-autoloader

script:
  - ./vendor/bin/phpunit -c phpunit.xml.dist
